### ISSUE TITLE
v0.14.x does not yet support ActiveSupport::Parameters

### ISSUE THREAD

**Issue by mathieujobin** [notEthan/api_hammer#56]
making this call on a rails 5 app won't work

```ruby
check_required_params(%w(event_uuid lot_uuid))
```

while this commit perfectly handled it
https://github.com/notEthan/api_hammer/pull/43/commits/e78b2828c9f3be3e5f934e5bd1108cded8bb1d7c

**Comment by mathieujobin** [comment]
@notEthan I had to keep my branch for access, `check_required_params` is still broken for me in rails5.
the only working solution i found is this https://github.com/notEthan/api_hammer/pull/43/commits/e78b2828c9f3be3e5f934e5bd1108cded8bb1d7c

**Comment by notEthan** [comment]
yeah, working on getting this and the other issues into shape right now for a release today or tomorrow
